dist: trusty
language: ruby
rvm:
- 2.2.5
- 2.1.9
- 2.0.0-p648
script:
- bundle exec rake travis
matrix:
  include:
  - rvm: 2.3.1
    env: GCLOUD_BUILD_DOCS=true
notifications:
  slack:
    secure: Ksji5MDNOWnuzuyu9Hblbxse6kGLdH4kXyYkF98C+wawIGLSONWWkuA65wpdqSLtBN/79RCLMWoBzKAGX4xy9BL6Rxb3rLjAMT+FVur6II2yaApzyJ0dmTVeTXnkchPcrO27FK5taPb0Ghr86DUiG3OViY/q1N0AVALDYce5tfE=
