language: ruby
os:
- osx
osx_image: xcode8.3
before_install:
- rvm get head
- rvm requirements
- rvm install 2.0.0-p648
rvm:
- 2.4.1
- 2.3.5
- 2.2.8
- 2.1.10
- 2.0.0-p648
script:
- gem update --system
- gem install bundler
- bundle exec rake travis:build
notifications:
  slack:
    secure: Ksji5MDNOWnuzuyu9Hblbxse6kGLdH4kXyYkF98C+wawIGLSONWWkuA65wpdqSLtBN/79RCLMWoBzKAGX4xy9BL6Rxb3rLjAMT+FVur6II2yaApzyJ0dmTVeTXnkchPcrO27FK5taPb0Ghr86DUiG3OViY/q1N0AVALDYce5tfE=
