AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-error_reporting.gemspec"
    - "lib/google/devtools/**/*"
    - "lib/google/cloud/error_reporting/v1beta1/**/*"
    - "Rakefile"
    - "test/**/*"

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 20
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Max: 30
Metrics/ParameterLists:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/FileName:
  Enabled: false # for lib/google-cloud-error_reporting.rb file
Lint/RescueException:
  Enabled: false # for by design Exception rescue in middleware.rb
Lint/AmbiguousOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false

